### ISSUE TITLE
Date error 

### ISSUE THREAD

**Issue by tb102122** [Booligoosh/covid19nsw#7]
Hey Ethan,

You have a small bug for the refresh date.
See the attached Screenshot.

Cheers Tobi

![Screenshot_20210915-142752_Chrome](https://user-images.githubusercontent.com/62531735/133370792-e09faaaa-3501-484f-b0e2-00b5ef257d27.jpg)

**Comment by Booligoosh** [comment]
Hey Tobias! That was actually because for some reason the Department of Health & NSW gov haven't uploaded the latest data to their sites, but I managed to do some digging around and get the more up-to-date data, so now it's up to the 12th!
https://github.com/Booligoosh/covid19nsw/commit/5b28653315f1514dd2d30b1b5232a4e5948844b2
